version: "3.8"
services:
    cache:
        container_name: test-cache
        image: redis:6.2.2-alpine3.13
        ports:
            - "9736:6379"
        volumes:
            - test-cache-data:/data
        restart: always
    db:
        container_name: test-db
        image: postgres:13.1-alpine
        ports:
            - "2345:5432"
        environment:
            #NOTE: default DB_DEV_PASS value could be changed in .env
            POSTGRES_PASSWORD: ${DB_DEV_PASS}
            POSTGRES_USER: ${DB_DEV_USER}
            POSTGRES_DB: ${DB_DEV_NAME}
        volumes:
            - test-db-data:/var/lib/postgresql/data
        restart: always
volumes:
    test-cache-data:
    test-db-data:
