version: "3.8"
services:
    server:
        container_name: app-server
        depends_on:
            - db
            - proxy
        build:
            context: .
            #dockerfile: Dockerfile_dev
            dockerfile: Dockerfile_prod
        ports:
            - "3000"
        volumes:
            #- ./:/usr/src/server/
            - ./logs/server.log:/usr/src/server/server.log
        restart: always
    db:
        container_name: app-db
        image: postgres:13.1-alpine
        ports:
            - "5432"
        environment:
            POSTGRES_PASSWORD: docNxgres
            POSTGRES_USER: docNxgres
            POSTGRES_DB: docNxgres
        volumes:
            - app-db-data:/var/lib/postgresql/data
        restart: always
    proxy:
        container_name: app-proxy
        image: nginx:1.19.6-alpine
        ports:
            - "8080:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./logs/proxy_access.log:/var/log/nginx/proxy_access.log
            - ./src/public:/var/www
        restart: always
volumes:
    app-db-data:
