version: "3.8"
services:
    server:
        container_name: app-server
        depends_on:
            - db
            - proxy
        build:
            context: .
            dockerfile: Dockerfile_prod
        ports:
            - "3000"
        environment:
            SERVER_PORT: 3000
        volumes:
            - ./logs/server.log:/usr/src/server/logs/server.log
        restart: always
    db:
        container_name: app-db
        image: postgres:13.1-alpine
        ports:
            - "5432"
        environment:
            #NOTE: default DB_PROD_PASS value should be changed in .env
            POSTGRES_PASSWORD: ${DB_PROD_PASS}
            POSTGRES_USER: ${DB_PROD_USER}
            POSTGRES_DB: ${DB_PROD_NAME}
        volumes:
            - app-db-data:/var/lib/postgresql/data
        restart: always
    proxy:
        container_name: app-proxy
        image: nginx:1.19.6-alpine
        ports:
            - "8080:80"
        environment:
            LOG_FORMAT: ${LOG_FORMAT}
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./default.conf.template:/etc/nginx/templates/default.conf.template
            - ./logs/proxy_access.log:/var/log/nginx/proxy_access.log
            - ./src/public:/var/www
        restart: always
volumes:
    app-db-data:
